name: Test

on:
    pull_request:
        types: [opened, reopened, synchronize]
        branches:
            - main

jobs:
  test:
    name: Smoke test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.2
      - name: smoke-tests
        run: |
          go run mdrss.go --config test/config update
          cat index.xml

  linter:
    name: linter check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.21.2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.58
